version: '3.8'

services:
  home-api:
    image: ghcr.io/christiankaseburg/home-api:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - PORT=8080

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./home-web-dist:/var/www/home-web
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - home-api
